name: erates

services:

  app:
    container_name: erates_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://root:toor@mongodb:27017
      - SECRET_KEY=your_secret_key
      - TOKEN_EXPIRE_MINUTES=60
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: erates_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local